In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('Clean_data.csv')
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
Unnamed: 0           10000 non-null int64
CreditScore          10000 non-null int64
Tenure               10000 non-null int64
Balance              10000 non-null float64
NumOfProducts        10000 non-null int64
HasCrCard            10000 non-null int64
IsActiveMember       10000 non-null int64
EstimatedSalary      10000 non-null float64
Exited               10000 non-null int64
Geography_Germany    10000 non-null int64
Geography_Spain      10000 non-null int64
Gender_Male          10000 non-null int64
Age_(10, 20]         10000 non-null int64
Age_(20, 30]         10000 non-null int64
Age_(30, 40]         10000 non-null int64
Age_(40, 50]         10000 non-null int64
Age_(50, 60]         10000 non-null int64
Age_(60, 70]         10000 non-null int64
Age_(70, 80]         10000 non-null int64
Age_(80, 90]         10000 non-null int64
dtypes: float64(2), int64(18)
memory usage: 1.5 

Unnamed: 0  CreditScore  Tenure    Balance  NumOfProducts  HasCrCard  \
0           0          619       2       0.00              1          1   
1           1          608       1   83807.86              1          0   
2           2          502       8  159660.80              3          1   
3           3          699       1       0.00              2          0   
4           4          850       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0               1        101348.88       1                  0   
1               1        112542.58       0                  0   
2               0        113931.57       1                  0   
3               0         93826.63       0                  0   
4               1         79084.10       0                  0   

   Geography_Spain  Gender_Male  Age_(10, 20]  Age_(20, 30]  Age_(30, 40]  \
0                0            0             0             0             0   
1                1            0             0             0             0   
2                0            0             0             0             0   
3                0            0             0             0             1   
4                1            0             0             0             0   

   Age_(40, 50]  Age_(50, 60]  Age_(60, 70]  Age_(70, 80]  Age_(80, 90]  
0             1             0             0             0             0  
1             1             0             0             0             0  
2             1             0             0             0             0  
3             0             0             0             0             0  
4             1             0             0             0             0

In [3]:
feat = df.drop(columns=['Exited'],axis=1)
label = df["Exited"]

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(feat,label,test_size=0.3)

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
sc_x = StandardScaler()
X_train = sc_x.fit_transform(X_train)
X_test = sc_x.fit_transform(X_test)

In [8]:
from sklearn.svm import SVC

In [11]:
support_vector_classifier = SVC(kernel='rbf')
support_vector_classifier.fit(X_train,y_train)
y_pred_svc = support_vector_classifier.predict(X_test)

In [13]:
from sklearn.metrics import confusion_matrix
cm_support_vector_classifier = confusion_matrix(y_test,y_pred_svc)
print(cm_support_vector_classifier,end='\n\n')

[[2309   60]
 [ 398  233]]



In [15]:
numerator = cm_support_vector_classifier[0][0] + cm_support_vector_classifier[1][1]

denominator = sum(cm_support_vector_classifier[0]) + sum(cm_support_vector_classifier[1])

acc_svc = (numerator/denominator)*100

print("Accuracy :", round(acc_svc,2),"%")

Accuracy : 84.73 %


In [16]:
from sklearn.model_selection import cross_val_score
cross_val_svc = cross_val_score(estimator = SVC(kernel = 'rbf'), X = X_train, y = y_train, cv = 10, n_jobs = -1)
print("Cross Validation Accuracy : ",round(cross_val_svc.mean() * 100 , 2),"%")

Cross Validation Accuracy :  85.74 %


In [17]:
# random forest
from sklearn.ensemble import RandomForestClassifier

In [21]:
random_forest_classifier = RandomForestClassifier()
random_forest_classifier.fit(X_train,y_train)
y_pred_rfc = random_forest_classifier.predict(X_test)

C:\Users\natel\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [22]:
cm_random_forest_classifier = confusion_matrix(y_test,y_pred_rfc)
print(cm_random_forest_classifier,end="\n\n")

[[2274   95]
 [ 395  236]]



In [23]:
numerator = cm_random_forest_classifier[0][0] + cm_random_forest_classifier[1][1]
denominator = sum(cm_random_forest_classifier[0]) + sum(cm_random_forest_classifier[1])
acc_rfc = (numerator/denominator) * 100
print("Accuracy : ",round(acc_rfc,2),"%")

Accuracy :  83.67 %


In [24]:
# cross validation
cross_val_rfc = cross_val_score(estimator=RandomForestClassifier(), X=X_train, y=y_train, cv=10, n_jobs=-1)
print("Cross Validation Accuracy : ",round(cross_val_rfc.mean() * 100 , 2),"%")

Cross Validation Accuracy :  84.63 %


In [25]:
from xgboost import XGBClassifier

In [26]:
xgb_classifier = XGBClassifier()
xgb_classifier.fit(X_train,y_train)
y_pred_xgb = xgb_classifier.predict(X_test)

In [27]:
cm_xgb_classifier = confusion_matrix(y_test,y_pred_xgb)
print(cm_xgb_classifier,end='\n\n')

[[2311   58]
 [ 378  253]]



In [28]:
numerator = cm_xgb_classifier[0][0] + cm_xgb_classifier[1][1]
denominator = sum(cm_xgb_classifier[0]) + sum(cm_xgb_classifier[1])
acc_xgb = (numerator/denominator) * 100
print("Accuracy : ",round(acc_xgb,2),"%")

Accuracy :  85.47 %


In [29]:
cross_val_xgb = cross_val_score(estimator=XGBClassifier(), X=X_train, y=y_train, cv=10, n_jobs=-1)
print("Cross Validation Accuracy : ",round(cross_val_xgb.mean() * 100 , 2),"%")

Cross Validation Accuracy :  86.09 %
